baseURL = 'https://ieri.sh/'
languageCode = 'en-us'
title = "IERI.SH"
theme = ["github.com/imfing/hextra"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false

[params]
  description = "Offensive Systems Research | Kernel | C2"
  favicon = "/favicon.ico"
  
  [params.theme]
    default = "dark"
    displayToggle = false

  [params.search]
    enable = true
    type = "flexsearch"

  [params.sidebar]
    enable = true
    autoCollapse = true
    
  [params.footer]
    enable = true
    displayCopyright = false

  [params.navbar]
    displayTitle = true
    displayLogo = true

  [params.navbar.logo]
      path = "/images/logo.png" 
      link = "/"
      width = 80
      height = 80